version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/www.aurbitrage.com/fullchain.pem:/app/server.crt
      - /etc/letsencrypt/live/www.aurbitrage.com/privkey.pem:/app/server.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dashboard-dev
      - dashboard-prod

  dashboard-dev:
    image: 637423524226.dkr.ecr.eu-north-1.amazonaws.com/aurbitrage-pricing:latest
    container_name: dashboard-dev
    environment:
      - NODE_ENV=development
      - GBQ_DATASET=aurbitrage_dataset_dev
    # No ports exposed directly; Nginx handles routing

  dashboard-prod:
    image: 637423524226.dkr.ecr.eu-north-1.amazonaws.com/aurbitrage-pricing:latest
    container_name: dashboard-prod
    environment:
      - NODE_ENV=dev
    # No ports exposed directly; Nginx handles routing
    restart: unless-stopped
